language: node_js
node_js:
- 4
- 10
sudo: false
cache:
  directories:
  - node_modules
notifications:
  email: false
before_script:
- npm prune
after_success:
- npm run test:coverage && npm run test:coverage:upload
- npm run semantic-release
branches:
  except:
    - /^v\d+\.\d+\.\d+$/
